# Generated by Django 5.0.1 on 2024-01-22 14:32

import django.db.models.deletion
import invmgmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('b_side', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('num_stars', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invmgmt.musician')),
            ],
            bases=(models.Model, invmgmt.models.ModelMixin),
        ),
    ]
